"""Build step of the PWA (there is no bundler): the service worker's file list and the cache version, and the app's version string.

The version is a hash of every file the service worker caches, so a changed file always means a new cache, and an unchanged tree always
means the same one (a test compares the committed files with what this module computes).
"""
from __future__ import annotations

import hashlib
import re
from pathlib import Path

SKIP_DIRS = {"tests", "tools"}
SKIP_FILES = {"sw.js"}                           # the worker can not cache itself
UNHASHED = {"js/build.js"}                       # carries the version, so it can not be part of it (but it IS cached)


def pwa_root() -> Path:
    return Path(__file__).resolve().parents[3] / "pwa"


def pwa_files(root: Path) -> list[str]:
    out = []
    for p in sorted(root.rglob("*")):
        rel = p.relative_to(root).as_posix()
        if p.is_file() and not (set(p.relative_to(root).parts[:-1]) & SKIP_DIRS) and rel not in SKIP_FILES:
            out.append(rel)
    return out


def version_of(root: Path, files: list[str]) -> str:
    h = hashlib.blake2b(digest_size=6)
    for f in (f for f in files if f not in UNHASHED):
        h.update(f.encode() + b"\0" + (root / f).read_bytes() + b"\0")
    return h.hexdigest()


def expected(root: Path) -> tuple[str, str, str]:
    """(version, new text of sw.js, new text of js/build.js)"""
    files = pwa_files(root)
    ver = version_of(root, files)
    sw = (root / "sw.js").read_text(encoding="utf-8")
    lst = "[\n" + "".join(f"  '{f}',\n" for f in ["./"] + files) + "]"
    sw = re.sub(r"const VERSION = '[^']*';", f"const VERSION = '{ver}';", sw)
    sw = re.sub(r"const FILES = \[.*?\];", lambda _: f"const FILES = {lst};", sw, flags=re.S)
    build = f"// Generated by `dataopen ctl pwa-build`: do not edit.\nexport const VERSION = '{ver}';\n"
    return ver, sw, build


def build(root: Path) -> str:
    ver, sw, build_js = expected(root)
    (root / "sw.js").write_text(sw, encoding="utf-8")
    (root / "js" / "build.js").write_text(build_js, encoding="utf-8")
    return ver


def is_current(root: Path) -> bool:
    _, sw, build_js = expected(root)
    f = root / "js" / "build.js"
    return (root / "sw.js").read_text(encoding="utf-8") == sw and f.exists() and f.read_text(encoding="utf-8") == build_js
