"""Compute budget, host (CPU) benchmark and the on-device RKNN benchmark script.

The targets are < 4 ms latency and > 240 FPS at 640x640 INT8 on a Rockchip NPU. Nothing here can MEASURE the NPU: the numbers
from `latency_budget` are napkin arithmetic to decide which model size is worth converting, and `rknn_bench_script` writes the
program that produces the real numbers on the board.
"""
from __future__ import annotations

import time
from pathlib import Path
from typing import Optional

import numpy as np


def latency_budget(macs: float, tops: float = 6.0, utilization: tuple[float, ...] = (0.2, 0.35, 0.5), cores: int = 3) -> dict:
    """Pure-compute time of `macs` multiply-accumulates on an NPU with `tops` INT8 TOPS (RK3588: 3 cores x 2 TOPS).

    One MAC = 2 ops. `utilization` is the fraction of peak that dense 3x3 convolutions reach in practice (memory-bound layers,
    layout conversions and the host copy-in/out come on top). Single-core numbers use tops/cores. This bounds the answer from
    below; it is not a prediction."""
    ops = 2.0 * macs
    out = {"gmacs": round(macs / 1e9, 3)}
    for u in utilization:
        out[f"all_cores_ms@{int(u * 100)}%"] = round(ops / (tops * 1e12 * u) * 1e3, 2)
        out[f"one_core_ms@{int(u * 100)}%"] = round(ops / (tops / cores * 1e12 * u) * 1e3, 2)
    one = out[f"one_core_ms@{int(utilization[1] * 100)}%"]
    out["fps_3_cores_pipelined@35%"] = round(1e3 / one * cores, 1)
    return out


def bench_onnx(path: str | Path, runs: int = 100, warmup: int = 10, threads: int = 0) -> dict:
    """CPU latency of an ONNX model with random input: a host-side sanity number, NOT the NPU."""
    import onnxruntime as ort
    so = ort.SessionOptions()
    if threads:
        so.intra_op_num_threads = threads
    sess = ort.InferenceSession(str(path), sess_options=so, providers=["CPUExecutionProvider"])
    inp = sess.get_inputs()[0]
    shape = [d if isinstance(d, int) else 1 for d in inp.shape]
    rng = np.random.default_rng(0)
    x = rng.integers(0, 256, shape).astype(np.uint8 if "uint8" in inp.type else np.float32)
    for _ in range(warmup):
        sess.run(None, {inp.name: x})
    ts = []
    for _ in range(runs):
        t = time.perf_counter()
        sess.run(None, {inp.name: x})
        ts.append((time.perf_counter() - t) * 1e3)
    a = np.array(ts)
    return {"runs": runs, "p50_ms": round(float(np.percentile(a, 50)), 3), "p95_ms": round(float(np.percentile(a, 95)), 3),
            "p99_ms": round(float(np.percentile(a, 99)), 3), "mean_ms": round(float(a.mean()), 3), "device": "host CPU (not the NPU)"}


RKNN_BENCH = '''"""Generated by `dataopen detector bench --rknn-script`: latency and throughput of an .rknn model ON THE BOARD.
Needs rknn-toolkit-lite2 (rknnlite) on the Rockchip device. NOT run in the dataopen repository.
    python {name} --model {model} --runs 2000
Targets: p99 latency < {lat_ms} ms single stream, aggregate throughput > {fps} FPS.
"""
import argparse, json, statistics, threading, time
import numpy as np
from rknnlite.api import RKNNLite

ap = argparse.ArgumentParser()
ap.add_argument("--model", default="{model}")
ap.add_argument("--runs", type=int, default=2000)
ap.add_argument("--warmup", type=int, default=50)
ap.add_argument("--size", type=int, default={size})
a = ap.parse_args()

x = np.random.randint(0, 256, (1, a.size, a.size, 3), dtype=np.uint8)       # NHWC uint8, like the camera frame


def make(core_mask):
    r = RKNNLite()
    assert r.load_rknn(a.model) == 0
    assert r.init_runtime(core_mask=core_mask) == 0
    return r


# 1) single-stream latency using ALL cores on one frame (core fusion), then one core alone
res = {{}}
for name, mask in (("all_cores", RKNNLite.NPU_CORE_0_1_2), ("core0", RKNNLite.NPU_CORE_0)):
    r = make(mask)
    for _ in range(a.warmup):
        r.inference(inputs=[x])
    ts = []
    for _ in range(a.runs):
        t = time.perf_counter()
        r.inference(inputs=[x])
        ts.append((time.perf_counter() - t) * 1e3)
    ts.sort()
    res[name] = {{"p50_ms": round(ts[len(ts) // 2], 3), "p99_ms": round(ts[int(len(ts) * 0.99) - 1], 3),
                  "mean_ms": round(statistics.mean(ts), 3)}}
    r.release()

# 2) throughput: three threads, one NPU core each, separate frames
masks = [RKNNLite.NPU_CORE_0, RKNNLite.NPU_CORE_1, RKNNLite.NPU_CORE_2]
done = [0, 0, 0]
stop = time.perf_counter() + 10.0


def worker(i):
    r = make(masks[i])
    while time.perf_counter() < stop:
        r.inference(inputs=[x])
        done[i] += 1
    r.release()


th = [threading.Thread(target=worker, args=(i,)) for i in range(3)]
t0 = time.perf_counter()
[t.start() for t in th]
[t.join() for t in th]
res["throughput_fps_3_cores"] = round(sum(done) / (time.perf_counter() - t0), 1)
res["meets_latency"] = res["all_cores"]["p99_ms"] < {lat_ms}
res["meets_throughput"] = res["throughput_fps_3_cores"] > {fps}
print(json.dumps(res, indent=2))
'''


def rknn_bench_script(path: str | Path, model: str = "apollo_s_int8.rknn", size: int = 640, lat_ms: float = 4.0,
                      fps: float = 240.0) -> Path:
    path = Path(path)
    path.write_text(RKNN_BENCH.format(name=path.name, model=model, size=size, lat_ms=lat_ms, fps=fps))
    return path


def meets_targets(measured: dict, lat_ms: float = 4.0, fps: float = 240.0) -> Optional[list[str]]:
    """Failures for a result dict produced by the on-device script (None when a number is missing)."""
    try:
        bad = []
        if not measured["all_cores"]["p99_ms"] < lat_ms:
            bad.append(f"p99 latency {measured['all_cores']['p99_ms']} ms >= {lat_ms} ms")
        if not measured["throughput_fps_3_cores"] > fps:
            bad.append(f"throughput {measured['throughput_fps_3_cores']} FPS <= {fps}")
        return bad
    except KeyError:
        return None
