/* Generated by dataopen.detector.structs: do not edit. Little endian, packed. */
#ifndef APOLLO_DETECTION_H
#define APOLLO_DETECTION_H
#include <stdint.h>

#define APOLLO_MAGIC 0x4F4C5041u /* 'APLO' */
#define APOLLO_VERSION 2
#define APOLLO_NUM_KEYPOINTS 12
#define APOLLO_MAX_DETECTIONS 20
#define APOLLO_Q 16 /* fixed point: pixels = value / 16 */

#pragma pack(push, 1)
typedef struct {
    uint8_t  class_id;                       /* index into the schema's classes (0 = player_ct, 1 = player_t) */
    uint8_t  confidence;                     /* score * 255 */
    uint16_t vis_mask;                       /* bit i set = keypoint i visible (v == 2) */
    uint16_t track_id;                       /* 0 = untracked */
    uint16_t bbox[4];                        /* x, y, w, h in Q12.4 pixels (model-input space) */
    int16_t  keypoints[APOLLO_NUM_KEYPOINTS][2]; /* x, y in Q12.4 pixels (model-input space) */
    uint8_t  kp_confidence[APOLLO_NUM_KEYPOINTS]; /* calibrated keypoint score * 255 */
} ApolloDetection;

typedef struct {
    uint32_t magic;                          /* APOLLO_MAGIC */
    uint16_t version;                        /* APOLLO_VERSION */
    uint8_t  n_keypoints;
    uint8_t  max_detections;
    uint32_t schema_hash;                    /* blake2b-32 of keypoint and class names: consumers refuse a mismatch */
    uint32_t frame_id;
    uint32_t timestamp_us;
    uint8_t  detection_count;                /* <= APOLLO_MAX_DETECTIONS */
    uint8_t  avg_scene_brightness;           /* mean luma 0..255 of the input frame */
    uint8_t  flags;
    uint8_t  reserved;
    float    letterbox_scale;                /* camera px * scale + pad = model-input px */
    int16_t  pad_x, pad_y;
    uint16_t src_w, src_h;                   /* camera frame size */
    ApolloDetection detections[APOLLO_MAX_DETECTIONS];
} KeypointArray;
#pragma pack(pop)

_Static_assert(sizeof(ApolloDetection) == 74, "ApolloDetection layout");
_Static_assert(sizeof(KeypointArray) == 1516, "KeypointArray layout");
#endif
