/* Hostile-input driver for the bridge core, built with -fsanitize=address,undefined (trap on the first finding).
 * seeds.h (generated by the test from the real Python descriptors and parameters) provides known-good inputs that are then
 * mutated at random; every parse result is checked for self-consistency, every report for the per-axis output invariants. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "bridge.h"
#include "seeds.h"

static uint64_t rng_s = 88172645463325252ull;
static uint32_t rnd(void) { rng_s ^= rng_s << 13; rng_s ^= rng_s >> 7; rng_s ^= rng_s << 17; return (uint32_t)(rng_s >> 11); }
static void fail(const char *m) { fprintf(stderr, "FUZZ FAIL: %s\n", m); abort(); }

static void mutate(uint8_t *b, uint32_t n) {
    uint32_t k = 1 + rnd() % 6;
    while (k-- && n) {
        uint32_t i = rnd() % n;
        switch (rnd() % 4) {
        case 0: b[i] = (uint8_t)rnd(); break;
        case 1: b[i] ^= (uint8_t)(1u << (rnd() & 7)); break;
        case 2: b[i] = (uint8_t)(rnd() & 1 ? 0xFF : 0x00); break;
        default: if (n > 1) b[i] = b[rnd() % n]; break;
        }
    }
}

static void check_map(const hid_map_t *m, uint16_t len) {
    if (m->n > HID_MAX_RIDS) fail("n > max");
    for (int i = 0; i < m->n; i++) {
        const hid_motion_t *o = &m->m[i];
        if (o->size_x < 1 || o->size_x > 16 || o->size_y < 1 || o->size_y > 16) fail("axis size");
        if ((uint32_t)o->off_x + o->size_x > (uint32_t)o->len * 8 || (uint32_t)o->off_y + o->size_y > (uint32_t)o->len * 8) fail("axis outside report");
        if (o->btn_n > 32) fail("buttons");
        if (o->len > 8192) fail("report len");
    }
    (void)len;
}

static void fuzz_descriptors(long n) {
    uint8_t buf[2048];
    const uint8_t *seeds[] = {SEED_RD_BOOT, SEED_RD_M16, SEED_RD_LOGI, SEED_RD_HIDPP, SEED_RD_KBD};
    const uint16_t lens[] = {sizeof SEED_RD_BOOT, sizeof SEED_RD_M16, sizeof SEED_RD_LOGI, sizeof SEED_RD_HIDPP, sizeof SEED_RD_KBD};
    for (long it = 0; it < n; it++) {
        uint16_t len;
        if (it % 5 == 0) { len = (uint16_t)(rnd() % 1100); for (uint16_t i = 0; i < len; i++) buf[i] = (uint8_t)rnd(); }
        else { int s = (int)(rnd() % 5); len = lens[s]; memcpy(buf, seeds[s], len); mutate(buf, len); if (rnd() % 8 == 0) len = (uint16_t)(rnd() % (len + 1)); }
        hid_map_t m;
        int r = hid_parse(buf, len, &m);
        if (r == HID_OK) { if (m.n == 0) fail("OK without motion"); check_map(&m, len); }
        else if (m.n != 0 && r != HID_E_NOXY) { /* errors may leave a partial map only for NOXY */ }
        /* every map must be usable by the editors on arbitrary report bytes */
        for (int k = 0; k < m.n; k++) {
            uint8_t rep[64];
            for (int i = 0; i < 64; i++) rep[i] = (uint8_t)rnd();
            if (m.uses_ids) rep[0] = m.m[k].report_id;
            const hid_motion_t *o = hid_find(&m, rep, 64);
            if (o && o->len <= 64) {
                int32_t x, y;
                uint8_t cp[64];
                memcpy(cp, rep, 64);
                hid_xy_get(o, rep, &x, &y);
                hid_xy_set(o, cp, (int32_t)rnd(), (int32_t)rnd());
                hid_xy_set(o, cp, x, y);
                if (memcmp(cp, rep, 64) != 0) fail("get/set round trip");
                (void)hid_buttons(o, rep, 64);
                uint8_t mk[64];
                hid_xy_mask(o, mk, 64);
                (void)hid_merge(o, cp, rep, 64);
            }
        }
    }
}

static void fuzz_config(long n) {
    static usb_image_t im;
    uint8_t buf[1200];
    for (long it = 0; it < n; it++) {
        uint16_t len = (uint16_t)sizeof SEED_CFG;
        if (it % 4 == 0) { len = (uint16_t)(9 + rnd() % 300); for (uint16_t i = 0; i < len; i++) buf[i] = (uint8_t)rnd(); buf[0] = 9; buf[1] = 2; buf[2] = (uint8_t)len; buf[3] = (uint8_t)(len >> 8); }
        else { memcpy(buf, SEED_CFG, len); mutate(buf, len); }
        img_init(&im);
        (void)img_set_device(&im, SEED_DEV, 18);
        (void)img_set_config(&im, buf, len);
        for (int i = 0; i < im.n_if; i++) {
            uint16_t w = img_rd_wanted(&im, i);
            if (w) (void)img_set_report_desc(&im, i, SEED_RD_LOGI, (uint16_t)(w < sizeof SEED_RD_LOGI ? w : sizeof SEED_RD_LOGI));
        }
        (void)img_finalize(&im, (int)(rnd() & 1));
        usb_setup_t s = {(uint8_t)rnd(), (uint8_t)rnd(), (uint16_t)rnd(), (uint16_t)rnd(), (uint16_t)rnd()};
        const uint8_t *d; uint16_t l;
        if (px_classify(&im, &s, &d, &l) == PX_SERVE) { if (l > s.wLength) fail("served more than wLength"); volatile uint8_t sink = d[l ? l - 1 : 0]; (void)sink; }
    }
}

static void put32(uint8_t *p, uint32_t v) { p[0] = (uint8_t)v; p[1] = (uint8_t)(v >> 8); p[2] = (uint8_t)(v >> 16); p[3] = (uint8_t)(v >> 24); }

static void send_frame(bridge_t *b, int64_t t, link_frame_t *f) { uint8_t raw[LINK_FRAME]; link_pack(raw, f); bridge_link_rx(b, t, raw); }

static void send_blob(bridge_t *b, int64_t t, uint8_t kind, const uint8_t *blob, int n, uint8_t serial) {
    int frags = (n + LINK_PAYLOAD - 1) / LINK_PAYLOAD;
    for (int i = 0; i < frags; i++) {
        link_frame_t f; memset(&f, 0, sizeof f);
        f.kind = kind; f.flags = serial; f.frag_idx = (uint8_t)i; f.frag_cnt = (uint8_t)frags; f.seq = (uint16_t)rnd();
        f.len = (uint16_t)(n - i * LINK_PAYLOAD > LINK_PAYLOAD ? LINK_PAYLOAD : n - i * LINK_PAYLOAD);
        memcpy(f.payload, blob + i * LINK_PAYLOAD, f.len);
        send_frame(b, t, &f);
    }
}

static void mutated_params(bridge_t *b, int64_t t, uint32_t gen) {
    static const int32_t picks[] = {0, 1, -1, 2147483647, (int32_t)0x80000000, 65536, -65536, 1 << 24, 1 << 28, 1 << 30, 100000000, 3};
    uint8_t blob[ASC_BLOB_LEN];
    memcpy(blob, SEED_ASC_BLOB, ASC_BLOB_LEN);
    put32(blob, gen);
    int k = (int)(rnd() % 5);
    for (int i = 0; i < k; i++) {
        int f = (int)(rnd() % 38);
        int32_t v = rnd() % 3 == 0 ? picks[rnd() % (sizeof picks / sizeof picks[0])] : (int32_t)((int64_t)((int32_t)(blob[16 + 4 * f] | blob[17 + 4 * f] << 8 | blob[18 + 4 * f] << 16 | (uint32_t)blob[19 + 4 * f] << 24)) * (int64_t)(1 + rnd() % 4) / (int64_t)(1 + rnd() % 4));
        put32(blob + 16 + 4 * f, (uint32_t)v);
    }
    put32(blob + ASC_BLOB_LEN - 4, link_crc32(blob, ASC_BLOB_LEN - 4));
    send_blob(b, t, LK_PARAMS_ASC, blob, ASC_BLOB_LEN, (uint8_t)(gen & 15));
    uint8_t tb[TRM_BLOB_LEN];
    memcpy(tb, SEED_TRM_BLOB, TRM_BLOB_LEN);
    put32(tb, gen);
    k = (int)(rnd() % 4);
    for (int i = 0; i < k; i++) {
        int f = (int)(rnd() % 15);
        int32_t v = rnd() % 2 ? picks[rnd() % (sizeof picks / sizeof picks[0])] : (int32_t)(rnd() % 100000);
        put32(tb + 16 + 4 * f, (uint32_t)v);
    }
    put32(tb + TRM_BLOB_LEN - 4, link_crc32(tb, TRM_BLOB_LEN - 4));
    send_blob(b, t, LK_PARAMS_TREMOR, tb, TRM_BLOB_LEN, (uint8_t)(gen & 15));
}

static void engage(bridge_t *b, int64_t *t) {
    bridge_dev_present(b, *t, 1);
    for (int i = 0; i < 4000 && b->fs.hw != HW_SEL_PROBE; i++) { *t += 1000; bridge_poll(b, *t); }
    if (b->fs.hw != HW_SEL_PROBE) fail("never probed");
    bridge_img_device(b, SEED_DEV, 18);
    bridge_img_config(b, SEED_CFG, sizeof SEED_CFG);
    for (int i = 0; i < bridge_img_n_if(b); i++) if (bridge_img_rd_wanted(b, i)) bridge_img_report_desc(b, i, SEED_RD_LOGI, sizeof SEED_RD_LOGI);
    if (bridge_img_done(b, *t) != IMG_OK) fail("image not ok");
    usb_setup_t s = {0x00, 9, 1, 0, 0};
    bridge_pc_forwarded_ok(b, *t, &s);
}

static void fuzz_runtime(long n, int split) {
    static bridge_t b;
    bridge_cfg_t c;
    bridge_cfg_defaults(&c);
    bridge_init(&b, &c);
    int64_t t = 1000000;
    bridge_set_speed(&b, split ? BR_SPEED_HS : BR_SPEED_FS);
    bridge_boot(&b, t, RESET_POWER, 0);
    engage(&b, &t);
    uint32_t gen = 1;
    mutated_params(&b, t, gen);
    uint8_t rep[8], out[8];
    const uint8_t *seeds[1] = {SEED_RD_LOGI};
    (void)seeds;
    int64_t cum_in = 0, cum_out = 0;
    (void)cum_in; (void)cum_out;
    for (long it = 0; it < n; it++) {
        uint32_t what = rnd() % 1000;
        t += (rnd() % 50 == 0) ? (int64_t)(rnd() % 3000000) : (int64_t)(split ? 125 : 1000) + (int64_t)(rnd() % 300);
        if (what < 700) {
            memset(rep, 0, sizeof rep);
            rep[0] = (uint8_t)(rnd() % 8 == 0 ? rnd() : 1);
            int32_t dx = (rnd() % 4 == 0) ? (int32_t)(rnd() % 4095) - 2047 : (int32_t)(rnd() % 61) - 30;
            int32_t dy = (rnd() % 4 == 0) ? (int32_t)(rnd() % 4095) - 2047 : (int32_t)(rnd() % 61) - 30;
            for (int i = 0; i < 8; i++) rep[i] = (uint8_t)(rep[i] | (i && rnd() % 3 == 0 ? rnd() : 0));
            rep[0] = (rnd() % 16 == 0) ? (uint8_t)rnd() : 1;
            hid_motion_t m; memset(&m, 0, sizeof m);
            m.size_x = m.size_y = 12; m.off_x = 24; m.off_y = 36; m.len = 8;
            hid_xy_set(&m, rep, dx, dy);
            bridge_poll(&b, t);
            uint16_t used = (uint16_t)(rnd() % 20 == 0 ? rnd() % 9 : 8);
            memset(out, 0xA5, sizeof out);
            int changed = bridge_mouse_in(&b, t, 0x81, rep, used, out);
            (void)changed;
            if (rep[0] == 1 && used == 8) {
                int32_t ix, iy, ox, oy;
                hid_xy_get(&m, rep, &ix, &iy);
                hid_xy_get(&m, out, &ox, &oy);
                if (b.fs.state == FS_ASSIST && !split) {
                    int32_t a[2] = {ix, ox}, d[2] = {iy, oy};
                    if (abs(a[1]) > abs(a[0]) || (a[1] != 0 && (a[1] > 0) != (a[0] > 0)) || (a[0] == 0 && a[1] != 0)) fail("axis x invariant");
                    if (abs(d[1]) > abs(d[0]) || (d[1] != 0 && (d[1] > 0) != (d[0] > 0)) || (d[0] == 0 && d[1] != 0)) fail("axis y invariant");
                }
            }
        } else if (what < 760) {
            mutated_params(&b, t, ++gen);
        } else if (what < 830) {                                   /* a scene with random objects, random capture time */
            link_frame_t f; memset(&f, 0, sizeof f);
            f.kind = LK_SCENE; f.seq = (uint16_t)rnd();
            int no = (int)(rnd() % 8);
            put32(f.payload, (uint32_t)(t - (int64_t)(rnd() % 200000) + (rnd() % 20 == 0 ? (int64_t)rnd() * 50 : 0)));
            f.payload[4] = (uint8_t)no;
            for (int i = 0; i < no && i < 5; i++) {
                uint8_t *q = f.payload + 8 + 20 * i;
                q[0] = (uint8_t)rnd(); q[1] = (uint8_t)rnd(); q[2] = (uint8_t)(rnd() & 1);
                put32(q + 4, rnd()); put32(q + 8, rnd()); put32(q + 12, rnd()); put32(q + 16, rnd());
            }
            f.len = (uint16_t)(8 + 20 * (no > 5 ? 5 : no));
            if (rnd() % 10 == 0) f.len = (uint16_t)(rnd() % 113);
            send_frame(&b, t, &f);
        } else if (what < 880) {
            link_frame_t f; memset(&f, 0, sizeof f);
            f.kind = (uint8_t)rnd(); f.len = (uint16_t)(rnd() % 113); f.frag_cnt = (uint8_t)(rnd() % 5); f.frag_idx = (uint8_t)(rnd() % 4); f.flags = (uint8_t)rnd();
            for (int i = 0; i < f.len; i++) f.payload[i] = (uint8_t)rnd();
            send_frame(&b, t, &f);
        } else if (what < 900) {
            uint8_t raw[LINK_FRAME]; for (int i = 0; i < LINK_FRAME; i++) raw[i] = (uint8_t)rnd();
            bridge_link_rx(&b, t, raw);
        } else if (what < 930) {
            uint8_t fr[LINK_FRAME]; bridge_link_tx(&b, t, fr);
        } else if (what < 950) {
            bridge_panic(&b, t, (int)(rnd() & 1));
        } else if (what < 960) {
            bridge_note_cost(&b, t, rnd() % 600);
        } else if (what < 965) {
            bridge_usb_error(&b, t);
        } else if (what < 975) {
            link_frame_t f; memset(&f, 0, sizeof f); f.kind = LK_CMD; f.len = 4; f.payload[0] = (uint8_t)(rnd() % 4); send_frame(&b, t, &f);
        } else if (what < 985) {
            usb_setup_t s = {(uint8_t)rnd(), (uint8_t)rnd(), (uint16_t)rnd(), (uint16_t)rnd(), (uint16_t)rnd()};
            const uint8_t *d; uint16_t l;
            if (bridge_pc_setup(&b, &s, &d, &l) == PX_FORWARD && rnd() % 2) bridge_pc_forwarded_ok(&b, t, &s);
        } else if (what < 990) {
            bridge_pc_bus_reset(&b, t);
        } else {
            bridge_status_t st; bridge_status(&b, t, &st);
        }
        if (b.fs.state == FS_ASSIST && b.fs.latch_soft) fail("ASSIST under a latch");
    }
}

/* Parameters drawn uniformly (and at the extremes) from the ACCEPTED ranges, driven with hostile geometry and motion straight into the cores:
 * this is what justifies the range tables (no overflow, no division by zero for anything the bridge accepts). */
static int32_t draw(int32_t lo, int32_t hi) {
    switch (rnd() % 5) {
    case 0: return lo;
    case 1: return hi;
    case 2: return (int32_t)((int64_t)lo + (int64_t)(rnd() % 1000) * ((int64_t)hi - lo) / 1000 / 100);       /* near the low end */
    default: return (int32_t)((int64_t)lo + (int64_t)(((uint64_t)rnd() << 11 ^ rnd()) % ((uint64_t)((int64_t)hi - lo) + 1)));
    }
}

static void fuzz_ranges(long n) {
    for (long it = 0; it < n; it++) {
        asc_params_t ap; tremor_params_t tp;
        int32_t *pa = (int32_t *)&ap, *pt = (int32_t *)&tp;
        for (int i = 0; i < 38; i++) { int32_t lo, hi; bridge_param_range(0, i, &lo, &hi); pa[i] = draw(lo, hi); }
        for (int i = 0; i < 15; i++) { int32_t lo, hi; bridge_param_range(1, i, &lo, &hi); pt[i] = draw(lo, hi); }
        if (!bridge_asc_params_valid(&ap) || !bridge_tremor_params_valid(&tp)) fail("drawn params not valid");
        ap.enabled = 1; tp.enabled = 1;
        asc_state_t as; tremor_state_t ts;
        asc_reset(&as); tremor_reset(&ts);
        int64_t t = 1000000;
        int64_t px = 0, py = 0;
        for (int k = 0; k < 400; k++) {
            t += (rnd() % 30 == 0) ? (int64_t)(rnd() % 2000000) : 1000 + (int64_t)(rnd() % 400);
            int32_t dx = (rnd() % 6 == 0) ? (int32_t)(rnd() % 1023) - 511 : (int32_t)(rnd() % 41) - 20;
            int32_t dy = (rnd() % 6 == 0) ? (int32_t)(rnd() % 1023) - 511 : (int32_t)(rnd() % 41) - 20;
            asc_obj_t o; o.id = (int32_t)(rnd() % 3); o.has_appear = (int32_t)(rnd() & 1); o.t_appear_us = t - (int64_t)(rnd() % 600000);
            o.x = (int32_t)(rnd() % 3 == 0 ? (int32_t)rnd() : (int32_t)(rnd() % 4000000) - 2000000);
            o.y = (int32_t)(rnd() % 3 == 0 ? (int32_t)rnd() : (int32_t)(rnd() % 4000000) - 2000000);
            o.radius = (int32_t)(rnd() % 2 ? rnd() % 20000000 : rnd() % 200000);
            px += (int64_t)dx * 65536 / 4; py += (int64_t)dy * 65536 / 4;
            int32_t cx = (int32_t)(px > 1073741823 ? 1073741823 : (px < -1073741823 ? -1073741823 : px)), cy = (int32_t)(py > 1073741823 ? 1073741823 : (py < -1073741823 ? -1073741823 : py));
            asc_out_t ao;
            asc_tick(&ap, &as, t, dx, dy, cx, cy, rnd() % 8 ? &o : 0, &ao);
            int32_t fx, fy;
            tremor_tick(&tp, &ts, t, ao.dx, ao.dy, &fx, &fy);
            if (abs(ao.dx) > abs(dx) || abs(ao.dy) > abs(dy) || abs(fx) > abs(ao.dx) || abs(fy) > abs(ao.dy)) fail("core output exceeds its input");
            if (ao.k < ap.k_floor - 1 || ao.k > 65536) fail("K out of range");
        }
    }
}

int main(int argc, char **argv) {
    long n = argc > 1 ? atol(argv[1]) : 20000;
    if (argc > 2) rng_s = (uint64_t)atoll(argv[2]) * 2654435761u + 88172645463325252ull;
    fuzz_descriptors(n);
    fuzz_config(n / 4);
    fuzz_ranges(n / 2);
    fuzz_runtime(n * 10, 0);
    fuzz_runtime(n * 10, 1);
    printf("fuzz ok\n");
    return 0;
}
